# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyiOSMesserger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyiOSMesserger

  target 'MyiOSMessergerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyiOSMessergerUITests' do
    # Pods for testing
  end

end
